name: Docker Image CI

on:
  push:
    branches:
    - master
    - gh-pages

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tablegenerator:$(date +%s)
